import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const APP_DIR = path.join(ROOT, "app");
const OUT_FILE = path.join(ROOT, "lib", "wickedSearchIndex.generated.ts");

const SKIP_DIRS = new Set(["api", "_components"]);
const SKIP_FILES = new Set(["layout.tsx", "template.tsx", "loading.tsx", "error.tsx", "not-found.tsx"]);

function isSkippableDir(dirName) {
  return dirName.startsWith("_") || SKIP_DIRS.has(dirName);
}

function walk(dir, files = []) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const full = path.join(dir, entry.name);

    if (entry.isDirectory()) {
      if (!isSkippableDir(entry.name)) walk(full, files);
      continue;
    }

    if (entry.isFile()) {
      if (SKIP_FILES.has(entry.name)) continue;
      if (entry.name === "page.tsx" || entry.name === "page.jsx") {
        files.push(full);
      }
    }
  }

  return files;
}

function routeFromFile(filePath) {
  const rel = path.relative(APP_DIR, filePath); // e.g. grimoire/chakras/page.tsx
  const noFile = rel.replace(/\/page\.(tsx|jsx)$/, "");
  const route = "/" + noFile.replace(/\\/g, "/");
  return route === "/page.tsx" ? "/" : route;
}

function cleanSegment(seg) {
  // Strip numeric prefixes like 01-aries, 04-codex
  return seg.replace(/^\d{1,3}-/, "");
}

function titleCase(str) {
  return str
    .replace(/-/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function extractMetadataTitle(fileText) {
  // Matches: export const metadata = { title: "Something" }
  const m = fileText.match(/metadata\s*=\s*{[\s\S]*?title\s*:\s*["'`](.+?)["'`]/);
  return m ? m[1].trim() : null;
}

function extractFirstH1(fileText) {
  const m = fileText.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  if (!m) return null;
  return stripJSX(m[1]);
}

function extractFirstParagraph(fileText) {
  const m = fileText.match(/<p[^>]*>([\s\S]*?)<\/p>/i);
  if (!m) return null;
  const text = stripJSX(m[1]);
  return text.length ? text : null;
}

function stripJSX(input) {
  return input
    // remove {"..."} and { ... } blocks
    .replace(/{[\s\S]*?}/g, " ")
    // remove tags
    .replace(/<[^>]+>/g, " ")
    // decode common entities
    .replace(/&apos;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&amp;/g, "&")
    .replace(/&#39;/g, "'")
    // normalize whitespace
    .replace(/\s+/g, " ")
    .trim();
}

function buildFallbackTitleFromRoute(route) {
  const segs = route.split("/").filter(Boolean).map(cleanSegment);
  if (segs.length === 0) return "Domicile";
  return titleCase(segs[segs.length - 1]);
}

function buildSection(route) {
  const segs = route.split("/").filter(Boolean).map(cleanSegment);
  if (segs.length === 0) return "Site";
  const top = segs[0];
  return titleCase(top);
}

function buildBreadcrumb(route) {
  const segs = route.split("/").filter(Boolean).map(cleanSegment).map(titleCase);
  if (segs.length === 0) return "";
  if (segs.length === 1) return segs[0];
  return segs.join(" / ");
}

function sanitizeForSnippet(text, max = 140) {
  const t = (text || "").replace(/\s+/g, " ").trim();
  if (t.length <= max) return t;
  return t.slice(0, max - 1).trim() + "…";
}

function extractBodyText(fileText) {
  // Grab visible-ish text: headings + paragraphs
  const pieces = [];

  const h1 = extractFirstH1(fileText);
  if (h1) pieces.push(h1);

  const pMatches = [...fileText.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/gi)];
  for (const m of pMatches) {
    const t = stripJSX(m[1]);
    if (t) pieces.push(t);
  }

  return pieces.join(" ");
}

function escapeTSString(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\${/g, "\\${");
}

const pages = walk(APP_DIR);

const items = [];

for (const file of pages) {
  const text = fs.readFileSync(file, "utf8");
  const href = routeFromFile(file);

  // Title priority: metadata.title > first h1 > fallback from route
  const title =
    extractMetadataTitle(text) ||
    extractFirstH1(text) ||
    buildFallbackTitleFromRoute(href);

  // Snippet priority: first paragraph > empty
  const snippet =
    sanitizeForSnippet(extractFirstParagraph(text) || "");

  const bodyText = extractBodyText(text);

  items.push({
    title,
    href,
    section: buildSection(href),
    breadcrumb: buildBreadcrumb(href),
    snippet,
    bodyText,
  });
}

const output = `/* AUTO-GENERATED FILE. DO NOT EDIT.
Generated by scripts/generateSearchIndex.mjs
*/

export type WickedSearchItem = {
  title: string;
  href: string;
  section: string;
  breadcrumb: string;
  snippet: string;
  bodyText: string;
};

export const WICKED_SEARCH_INDEX: WickedSearchItem[] = [
${items
  .map((it) => {
    return `  {
    title: \`${escapeTSString(it.title)}\`,
    href: \`${escapeTSString(it.href)}\`,
    section: \`${escapeTSString(it.section)}\`,
    breadcrumb: \`${escapeTSString(it.breadcrumb)}\`,
    snippet: \`${escapeTSString(it.snippet)}\`,
    bodyText: \`${escapeTSString(it.bodyText)}\`,
  },`;
  })
  .join("\n")}
];
`;

fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
fs.writeFileSync(OUT_FILE, output, "utf8");

console.log(`Generated ${items.length} search entries -> lib/wickedSearchIndex.generated.ts`);